//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class artprove
    {
        public int id { get; set; }
        public string codpro { get; set; }
        public decimal nropro { get; set; }
        public decimal costo { get; set; }
        public decimal condpag { get; set; }
        public System.DateTime fecha { get; set; }
        public string codorigi { get; set; }
        public decimal moneda { get; set; }
        public decimal cotizacion { get; set; }
    }
}
