//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        public int id { get; set; }
        public int empresaid { get; set; }
        public int nropro { get; set; }
        public int nrocli { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal concepto { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal redondeo { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public string detalle { get; set; }
        public string moneda { get; set; }
        public decimal cotizacion { get; set; }
        public string simbolo { get; set; }
        public decimal debedoc { get; set; }
        public decimal haberdoc { get; set; }
        public string usuario { get; set; }
        public int movcja { get; set; }
        public int ctacon { get; set; }
        public bool pasoacont { get; set; }
        public int ctapase { get; set; }
        public string tipomov { get; set; }
        public string razsoc { get; set; }
        public int idusuario { get; set; }
        public decimal vuelto { get; set; }
        public decimal suefe { get; set; }
        public decimal sudoc { get; set; }
    }
}
