//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheques
    {
        public int id { get; set; }
        public int empresaid { get; set; }
        public decimal nroint { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fechacre { get; set; }
        public System.DateTime feching { get; set; }
        public string nroche { get; set; }
        public decimal banco { get; set; }
        public string nomban { get; set; }
        public decimal importe { get; set; }
        public decimal nrocli { get; set; }
        public string razsoc { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha1 { get; set; }
        public decimal nropro { get; set; }
        public string nomend { get; set; }
        public string abanco { get; set; }
        public string propio { get; set; }
        public string cta { get; set; }
        public string tipoop { get; set; }
        public string letraop { get; set; }
        public decimal puntoop { get; set; }
        public decimal numeroop { get; set; }
        public decimal gastos { get; set; }
        public string codpos { get; set; }
        public string observa { get; set; }
        public string checuit { get; set; }
        public string usuario { get; set; }
        public decimal nrolib { get; set; }
        public decimal movcja { get; set; }
        public bool noalaorden { get; set; }
        public string letrache { get; set; }
        public int sucursal { get; set; }
        public string cuenta { get; set; }
    }
}
