//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clictad
    {
        public decimal nrocli { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime hora { get; set; }
        public int tipodocid { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal importe1 { get; set; }
        public decimal importe2 { get; set; }
        public System.DateTime vence { get; set; }
        public decimal bonif { get; set; }
        public decimal impbonif { get; set; }
        public decimal cobro { get; set; }
        public decimal retiva { get; set; }
        public decimal retib { get; set; }
        public decimal retgan { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public decimal comiprod { get; set; }
        public decimal acreditar { get; set; }
        public decimal cotdoc { get; set; }
        public string simdoc { get; set; }
        public int id { get; set; }
        public int empresa { get; set; }
        public int clictaID { get; set; }
        public int acopionro { get; set; }
    }
}
