//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clicta
    {
        public decimal nrocli { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public decimal saldo { get; set; }
        public string tipdoco { get; set; }
        public string letrao { get; set; }
        public decimal puntoo { get; set; }
        public decimal numeroo { get; set; }
        public string observa { get; set; }
        public bool anulado { get; set; }
        public decimal bonif { get; set; }
        public decimal impbonif { get; set; }
        public decimal cobro { get; set; }
        public decimal retgan { get; set; }
        public decimal retiva { get; set; }
        public decimal retib { get; set; }
        public decimal codven { get; set; }
        public decimal comicob { get; set; }
        public decimal comicocl { get; set; }
        public decimal netocob { get; set; }
        public bool liquidada { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public decimal comiprod { get; set; }
        public decimal recimenu { get; set; }
        public decimal recimanu { get; set; }
        public decimal porcenp { get; set; }
        public decimal diaspag { get; set; }
        public System.DateTime fechafac { get; set; }
        public string nombreusu { get; set; }
        public bool verifi { get; set; }
        public string verifico { get; set; }
        public decimal cotdoc { get; set; }
        public string simdoc { get; set; }
        public string orirec { get; set; }
        public string motivo { get; set; }
        public string clave { get; set; }
        public int movcja { get; set; }
        public int id { get; set; }
        public int ivavenid { get; set; }
        public int empresa { get; set; }
        public int tipodocid { get; set; }
        public int acopionro { get; set; }
        public int tipodocido { get; set; }
        public int ivavenido { get; set; }
        public decimal totacopio { get; set; }
    }
}
