//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clienteModal
    {
        public int nrocli { get; set; }
        public string razsoc { get; set; }
        public string fantasia { get; set; }
        public string direcc { get; set; }
        public string cuit { get; set; }
        public string telef1 { get; set; }
        public string telef2 { get; set; }
        public string nombre { get; set; }
        public decimal codven { get; set; }
    }
}
