//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientePesupuesto
    {
        public int nrocli { get; set; }
        public string razsoc { get; set; }
        public string direcc { get; set; }
        public int localicod { get; set; }
        public string nombreLocali { get; set; }
        public string deptoNombre { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> provincia_id { get; set; }
        public string nombreProv { get; set; }
        public string pais { get; set; }
        public string cuit { get; set; }
        public int Iva { get; set; }
        public string descriIva { get; set; }
        public int tipodoc { get; set; }
        public decimal condicion { get; set; }
        public decimal lista { get; set; }
        public Nullable<decimal> codven { get; set; }
        public string nombreVende { get; set; }
        public int respon { get; set; }
        public string telef1 { get; set; }
        public decimal bonif { get; set; }
        public decimal bonif1 { get; set; }
        public decimal bonif2 { get; set; }
        public decimal bonif3 { get; set; }
        public decimal bonif4 { get; set; }
        public bool convenio { get; set; }
        public bool nopercib { get; set; }
        public decimal expreso { get; set; }
        public decimal cond_vta { get; set; }
    }
}
