//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int nrocli { get; set; }
        public string razsoc { get; set; }
        public string fantasia { get; set; }
        public string direcc { get; set; }
        public string direcom { get; set; }
        public int locali { get; set; }
        public string codpos { get; set; }
        public string telef1 { get; set; }
        public string telef2 { get; set; }
        public string fax { get; set; }
        public decimal expreso { get; set; }
        public string cuit { get; set; }
        public int respon { get; set; }
        public string ingbru { get; set; }
        public decimal zona { get; set; }
        public decimal totmen { get; set; }
        public System.DateTime feccom { get; set; }
        public decimal estcue1 { get; set; }
        public decimal codven { get; set; }
        public decimal comicob { get; set; }
        public decimal comis { get; set; }
        public decimal condicion { get; set; }
        public decimal lista { get; set; }
        public decimal bonif { get; set; }
        public decimal bonif1 { get; set; }
        public string contacto { get; set; }
        public decimal credito { get; set; }
        public string email { get; set; }
        public string pweb { get; set; }
        public decimal cond_vta { get; set; }
        public string observa { get; set; }
        public decimal pais { get; set; }
        public bool inhabilitado { get; set; }
        public System.DateTime fechalta { get; set; }
        public bool visualiza { get; set; }
        public int activi { get; set; }
        public int direntrega { get; set; }
        public string codprove { get; set; }
        public string monfac { get; set; }
        public bool incobrable { get; set; }
        public string clavepais { get; set; }
        public bool nopercib { get; set; }
        public bool masche { get; set; }
        public bool abonado { get; set; }
        public string habmunic { get; set; }
        public int sucuent { get; set; }
        public string cai { get; set; }
        public System.DateTime vencecai { get; set; }
        public string diavisi { get; set; }
        public string diaentre { get; set; }
        public string horario { get; set; }
        public string celular { get; set; }
        public int ctacon { get; set; }
        public bool moroso { get; set; }
        public decimal credias { get; set; }
        public bool bloqxcre { get; set; }
        public decimal bonif2 { get; set; }
        public decimal bonif3 { get; set; }
        public decimal bonif4 { get; set; }
        public bool merchan { get; set; }
        public string email1 { get; set; }
        public int tipodoc { get; set; }
        public decimal MontoPib { get; set; }
        public string clave { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public bool convenio { get; set; }
        public bool entdom { get; set; }
        public int id { get; set; }
        public bool hacerFCE { get; set; }
        public int imei { get; set; }
    }
}
