//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class concepto
    {
        public int codigo { get; set; }
        public string descri { get; set; }
        public int ctacon { get; set; }
        public bool inhabil { get; set; }
        public string grupo { get; set; }
        public int id { get; set; }
    }
}
