//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class configen
    {
        public int empresa { get; set; }
        public decimal impdec { get; set; }
        public decimal candec { get; set; }
        public bool factucont { get; set; }
        public string mensajefac { get; set; }
        public bool preciocero { get; set; }
        public bool presinclu { get; set; }
        public string pathfondo { get; set; }
        public byte[] fondo { get; set; }
        public string server { get; set; }
        public string nmonedacl { get; set; }
        public bool emiremi { get; set; }
        public bool retomapre { get; set; }
        public bool calcupeso { get; set; }
        public bool factexto { get; set; }
        public bool pedingre { get; set; }
        public bool pagoctdo { get; set; }
        public bool impricheq { get; set; }
        public bool stkxrep { get; set; }
        public bool imprireci { get; set; }
        public bool factenrep { get; set; }
        public bool desreciva { get; set; }
        public bool impripago { get; set; }
        public bool reci1hoja { get; set; }
        public decimal minretiva { get; set; }
        public bool detobli { get; set; }
        public bool nofsinstk { get; set; }
        public decimal recctacte { get; set; }
        public System.DateTime fechontro { get; set; }
        public bool finoc { get; set; }
        public decimal actustk { get; set; }
        public bool impricaja { get; set; }
        public bool veraplica { get; set; }
        public string monhis { get; set; }
        public bool pedidoaprob { get; set; }
        public bool fechaitemped { get; set; }
        public bool cheqpedi { get; set; }
        public bool stkypedi { get; set; }
        public bool noenlista { get; set; }
        public bool nosinpresup { get; set; }
        public decimal consrec { get; set; }
        public decimal gasgen { get; set; }
        public bool netart { get; set; }
        public bool genenc { get; set; }
        public string pathrece { get; set; }
        public bool nrrecman { get; set; }
        public bool reminode { get; set; }
        public bool pedidoprep { get; set; }
        public bool cambiacliped { get; set; }
        public decimal msgsevasolo { get; set; }
        public bool retuveib { get; set; }
        public bool norepitem { get; set; }
        public string letrache { get; set; }
        public bool reimpd { get; set; }
        public bool fcdesstk { get; set; }
        public int via { get; set; }
        public short ubicacionsalida { get; set; }
        public short ubicacionentrada { get; set; }
        public string GcSimboloCl { get; set; }
        public decimal GnCotizaCl { get; set; }
        public int id { get; set; }
        public string iplistados { get; set; }
        public decimal ivatasagral { get; set; }
        public decimal ivanoinscripto { get; set; }
        public string dominio { get; set; }
        public byte cond_vta { get; set; }
        public string iplocal { get; set; }
        public decimal minfec { get; set; }
    }
}
