//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class descxrub
    {
        public int id { get; set; }
        public decimal nrocli { get; set; }
        public decimal rubro { get; set; }
        public decimal boni1 { get; set; }
        public decimal boni2 { get; set; }
        public decimal boni3 { get; set; }
        public decimal boni4 { get; set; }
        public decimal boni5 { get; set; }
        public int empresaid { get; set; }
    }
}
