//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class detcompr
    {
        public int id { get; set; }
        public string codpro { get; set; }
        public string descri { get; set; }
        public decimal cant { get; set; }
        public decimal precio { get; set; }
        public decimal bonif { get; set; }
        public decimal bonif1 { get; set; }
        public decimal prexcant { get; set; }
        public string despacho { get; set; }
        public decimal bonito { get; set; }
        public decimal ivaartins { get; set; }
        public decimal ivartinoi { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public string ocompra { get; set; }
        public int ctacon { get; set; }
        public string monedacodigo { get; set; }
        public int ivacomid { get; set; }
        public int nropro { get; set; }
        public int empresa { get; set; }
        public int tipodocid { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal bonif2 { get; set; }
        public decimal bonif3 { get; set; }
        public decimal bonif4 { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipodocRto { get; set; }
        public string letraRto { get; set; }
        public decimal puntoRto { get; set; }
        public decimal numeroRto { get; set; }
        public int ubicacionid { get; set; }
    }
}
