//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class documen
    {
        public int nroint { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal nropro { get; set; }
        public System.DateTime vence { get; set; }
        public decimal importe { get; set; }
        public string estado { get; set; }
        public string observa { get; set; }
        public int nromanu { get; set; }
        public int movcja { get; set; }
        public int id { get; set; }
        public int empresaid { get; set; }
    }
}
