//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int id { get; set; }
        public string empresa1 { get; set; }
        public string titulares { get; set; }
        public string direccion { get; set; }
        public int localidad { get; set; }
        public string codpos { get; set; }
        public string telefono { get; set; }
        public string cuit { get; set; }
        public string brutos { get; set; }
        public string jubilacion { get; set; }
        public string internos { get; set; }
        public string titulo1 { get; set; }
        public string titulo2 { get; set; }
        public string email { get; set; }
        public string pweb { get; set; }
        public string pathlogo { get; set; }
        public string primerlin { get; set; }
        public string segunlin { get; set; }
        public string tercerlin { get; set; }
        public int nejerdef { get; set; }
        public int nejercicio { get; set; }
        public short condfiva { get; set; }
        public System.DateTime finiact { get; set; }
        public byte[] timestamp_column { get; set; }
        public string pathfondo { get; set; }
        public bool percib { get; set; }
        public decimal montopib { get; set; }
        public decimal percepib { get; set; }
        public bool retib { get; set; }
        public decimal montorib { get; set; }
        public decimal retnib { get; set; }
        public bool empxdefecto { get; set; }
        public string cotUsuario { get; set; }
        public string cotPasswd { get; set; }
        public string pathcot { get; set; }
        public short juridi { get; set; }
        public bool esagntPercepcion { get; set; }
        public bool esagntRetencion { get; set; }
        public bool entraxdefault { get; set; }
        public string cbu { get; set; }
        public bool promoind { get; set; }
        public bool retivap { get; set; }
        public bool retganp { get; set; }
        public bool despagiva { get; set; }
    }
}
