//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class factu
    {
        public string ARTICULO { get; set; }
        public string ASOCIADO { get; set; }
        public decimal BONIF { get; set; }
        public decimal BONIF1 { get; set; }
        public decimal BONIFTO { get; set; }
        public decimal CANASOC { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal CODVEN { get; set; }
        public string CONDICION { get; set; }
        public string DESCRI { get; set; }
        public string DETA { get; set; }
        public decimal IMPINT { get; set; }
        public decimal ITEM { get; set; }
        public decimal NROCLI { get; set; }
        public string OBSERVA { get; set; }
        public decimal ORDEN { get; set; }
        public decimal PRECIO { get; set; }
        public decimal PRECORIG { get; set; }
        public string RAZSOC { get; set; }
        public string TIPO { get; set; }
        public decimal TOTAL { get; set; }
        public int id { get; set; }
        public int empresa { get; set; }
        public int tipodocid { get; set; }
    }
}
