//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int id { get; set; }
        public int EmpresaId { get; set; }
        public decimal PUNTO { get; set; }
        public decimal CANTCOPIA { get; set; }
        public decimal CANTCOPIB { get; set; }
        public decimal CANTCOPICOT { get; set; }
        public decimal CANTCOPIE { get; set; }
        public decimal CANTCOPIPED { get; set; }
        public decimal CANTCOPIPRES { get; set; }
        public decimal CANTCOPIRE { get; set; }
        public decimal CANTCOPIRECI { get; set; }
        public decimal CANTRENGLA { get; set; }
        public decimal CANTRENGLB { get; set; }
        public decimal CANTRENGLCOMPR { get; set; }
        public decimal CANTRENGLCOTIZ { get; set; }
        public decimal CANTRENGLE { get; set; }
        public decimal CANTRENGLPEDI { get; set; }
        public decimal CANTRENGLREMI { get; set; }
        public decimal CANTRENPRES { get; set; }
        public decimal COMIMPF { get; set; }
        public decimal COTIZACION { get; set; }
        public decimal CREDITOA { get; set; }
        public decimal CREDITOB { get; set; }
        public decimal CREDITOE { get; set; }
        public decimal DEBITOA { get; set; }
        public decimal DEBITOB { get; set; }
        public decimal DEBITOE { get; set; }
        public decimal FACTURAA { get; set; }
        public decimal FACTURAB { get; set; }
        public decimal FACTURAE { get; set; }
        public bool FCELECBF { get; set; }
        public bool FCELECEX { get; set; }
        public bool FCELECT { get; set; }
        public bool GENEMOV { get; set; }
        public decimal HOJACOM { get; set; }
        public decimal HOJAVEN { get; set; }
        public bool IMPFIS { get; set; }
        public bool MULTIA { get; set; }
        public bool MULTIB { get; set; }
        public bool MULTIE { get; set; }
        public decimal OCOMPRA { get; set; }
        public decimal ORDEN { get; set; }
        public decimal ORDENPAGO { get; set; }
        public decimal PEDIDO { get; set; }
        public decimal PRESUP { get; set; }
        public decimal RECIBO { get; set; }
        public decimal APLICA { get; set; }
        public decimal REMITO { get; set; }
        public decimal REMITOINT { get; set; }
        public decimal SINDEFINIR { get; set; }
        public string descripcion { get; set; }
        public int depositoid { get; set; }
        public bool renglonfijo { get; set; }
        public bool ptoxdefecto { get; set; }
        public decimal FCPROFO { get; set; }
        public string direcc { get; set; }
        public int locali { get; set; }
        public decimal FCEA { get; set; }
        public decimal FCEB { get; set; }
        public decimal NDCA { get; set; }
        public decimal NDCB { get; set; }
        public decimal NCCA { get; set; }
        public decimal NCCB { get; set; }
        public byte COPIACA { get; set; }
        public byte COPIACB { get; set; }
        public short RENGCA { get; set; }
        public short RENGCB { get; set; }
    }
}
