//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class iva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iva()
        {
            this.provee = new HashSet<provee>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string docrelac { get; set; }
        public bool conAcrecAlicuta { get; set; }
        public bool PercIb { get; set; }
        public bool RetIB { get; set; }
        public bool discrimina { get; set; }
        public bool activo { get; set; }
        public int auximigra { get; set; }
        public int auximpfiscal { get; set; }
        public bool exentocf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provee> provee { get; set; }
    }
}
