//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class ivacom
    {
        public int id { get; set; }
        public decimal mes { get; set; }
        public decimal ano { get; set; }
        public int empresaid { get; set; }
        public int tipodocid { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal nropro { get; set; }
        public decimal codcondic { get; set; }
        public string razsoc { get; set; }
        public decimal provin { get; set; }
        public string cuit { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal neto { get; set; }
        public decimal neto1 { get; set; }
        public decimal exento { get; set; }
        public decimal retiva { get; set; }
        public decimal retgan { get; set; }
        public decimal retinbr { get; set; }
        public decimal retinbrcap { get; set; }
        public decimal subtot { get; set; }
        public decimal ivai { get; set; }
        public decimal ivanoi { get; set; }
        public decimal ivaidif { get; set; }
        public decimal ivanoidif { get; set; }
        public decimal total { get; set; }
        public decimal respon { get; set; }
        public decimal bonif { get; set; }
        public decimal bonitot { get; set; }
        public string condicion { get; set; }
        public decimal porcen1 { get; set; }
        public decimal porcen2 { get; set; }
        public decimal porcen1dif { get; set; }
        public decimal porcen2dif { get; set; }
        public decimal actustk { get; set; }
        public bool verificado { get; set; }
        public string observa { get; set; }
        public decimal internos { get; set; }
        public decimal retibcap { get; set; }
        public decimal retibrcap { get; set; }
        public decimal retsuss { get; set; }
        public decimal nrocli { get; set; }
        public decimal concepto { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public decimal nroret { get; set; }
        public bool cerrado { get; set; }
        public string cai { get; set; }
        public System.DateTime vencecai { get; set; }
        public decimal retinbotra { get; set; }
        public decimal nroiva { get; set; }
        public decimal nrogan { get; set; }
        public decimal nrocap { get; set; }
        public decimal nroib { get; set; }
        public decimal nrootra { get; set; }
        public decimal nroprov { get; set; }
        public decimal nrosus { get; set; }
        public int ctacon { get; set; }
        public int ctacon1 { get; set; }
        public int ctaconex { get; set; }
        public bool pasoacont { get; set; }
        public string nombreusu { get; set; }
        public decimal otrosimp { get; set; }
        public string monedacodigo { get; set; }
    }
}
