//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class ivaven
    {
        public int id { get; set; }
        public int empresaid { get; set; }
        public int tipodocid { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal hasta { get; set; }
        public decimal nrocli { get; set; }
        public string razsoc { get; set; }
        public string direcc { get; set; }
        public string locali { get; set; }
        public string codpos { get; set; }
        public decimal provin { get; set; }
        public string cuit { get; set; }
        public decimal subtot { get; set; }
        public decimal bonitot { get; set; }
        public decimal bonifto { get; set; }
        public decimal exento { get; set; }
        public decimal neto { get; set; }
        public decimal ivai { get; set; }
        public decimal ivanoi { get; set; }
        public decimal ivaidif { get; set; }
        public decimal ivanoidif { get; set; }
        public decimal total { get; set; }
        public decimal bonif { get; set; }
        public decimal codcondic { get; set; }
        public string condicion { get; set; }
        public decimal codven { get; set; }
        public string nomven { get; set; }
        public decimal respon { get; set; }
        public decimal comis { get; set; }
        public decimal retiva { get; set; }
        public decimal retgan { get; set; }
        public decimal retinb { get; set; }
        public decimal remito { get; set; }
        public string observa { get; set; }
        public decimal comiprod { get; set; }
        public decimal comicli { get; set; }
        public bool liquidada { get; set; }
        public decimal porins { get; set; }
        public decimal pornoi { get; set; }
        public decimal porinsdif { get; set; }
        public decimal pornoidif { get; set; }
        public System.DateTime vence { get; set; }
        public string ocompra { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public decimal nrorepa { get; set; }
        public decimal nrollevo { get; set; }
        public bool cumplido { get; set; }
        public bool bajostk { get; set; }
        public decimal porcenib { get; set; }
        public bool cerrado { get; set; }
        public string cai { get; set; }
        public System.DateTime vencecai { get; set; }
        public string obsrepa { get; set; }
        public decimal cothis { get; set; }
        public int ctacon { get; set; }
        public bool pasoacont { get; set; }
        public int ctaconex { get; set; }
        public string sucursal { get; set; }
        public string nombreusu { get; set; }
        public decimal internos { get; set; }
        public decimal lisfac { get; set; }
        public string notavta { get; set; }
        public bool esadeta { get; set; }
        public int tipocuit { get; set; }
        public string cae { get; set; }
        public string idpetic { get; set; }
        public System.DateTime vencecae { get; set; }
        public string numerofe { get; set; }
        public string ctapase { get; set; }
        public string nrolibe { get; set; }
        public string contac { get; set; }
        public decimal estcue { get; set; }
        public System.DateTime exfecsalida { get; set; }
        public string exnroembar { get; set; }
        public string expuertosale { get; set; }
        public string expuertollega { get; set; }
        public string exnrobl { get; set; }
        public string exdestinofinal { get; set; }
        public string exincoterms { get; set; }
        public System.DateTime exfechafab { get; set; }
        public string exorigen { get; set; }
        public string expackag { get; set; }
        public string exmarca { get; set; }
        public string exmaterial { get; set; }
        public string exhscode { get; set; }
        public string obsrepgen { get; set; }
        public string exforwarder { get; set; }
        public decimal kilos { get; set; }
        public string moneda { get; set; }
        public decimal juridEntrega { get; set; }
        public decimal recargo { get; set; }
        public string departamento { get; set; }
        public string provincia { get; set; }
        public int localiid { get; set; }
    }
}
