//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOpxRubro
    {
        public string codpro { get; set; }
        public string descri { get; set; }
        public Nullable<int> unidades { get; set; }
        public int porsunid { get; set; }
        public Nullable<int> cantidad { get; set; }
        public int porscant { get; set; }
        public Nullable<decimal> precio { get; set; }
        public decimal costo { get; set; }
        public Nullable<int> nrofac { get; set; }
        public Nullable<decimal> pendientes { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int codRub { get; set; }
        public string descriRub { get; set; }
        public decimal codSubRub { get; set; }
        public string descriSubRu { get; set; }
        public int codTipoArt { get; set; }
        public string descriTipoArt { get; set; }
        public int proveed { get; set; }
        public Nullable<decimal> codven { get; set; }
        public Nullable<decimal> nrocli { get; set; }
        public string tipodoc { get; set; }
    }
}
