//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPrecios
    {
        public string codpro { get; set; }
        public string descri { get; set; }
        public int unimed { get; set; }
        public decimal precio1 { get; set; }
        public decimal precio2 { get; set; }
        public decimal precio3 { get; set; }
        public decimal precio4 { get; set; }
        public decimal precio5 { get; set; }
        public decimal precio6 { get; set; }
        public decimal costo { get; set; }
        public int codRubro { get; set; }
        public string descriRubro { get; set; }
        public decimal codSubrub { get; set; }
        public string descriSub { get; set; }
        public int marca { get; set; }
        public string descrimarcas { get; set; }
        public int codprovee { get; set; }
        public string descriProveed { get; set; }
        public bool oferta { get; set; }
        public decimal lista { get; set; }
        public System.DateTime fechaact { get; set; }
        public string moneda { get; set; }
        public decimal ivagrupo { get; set; }
        public decimal porcen1 { get; set; }
        public string simbolo { get; set; }
        public bool incluido { get; set; }
    }
}
