//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVentasPorProductodsadsdassd
    {
        public Nullable<int> codMarca { get; set; }
        public string descriMarcas { get; set; }
        public Nullable<int> codRubro { get; set; }
        public string rubrosDescri { get; set; }
        public Nullable<decimal> subrub { get; set; }
        public string descriSubRub { get; set; }
        public Nullable<decimal> codven { get; set; }
        public string nombreVende { get; set; }
        public Nullable<int> nrocli { get; set; }
        public string razsocCli { get; set; }
        public Nullable<int> codProvee { get; set; }
        public string razsocProvee { get; set; }
        public string tipodoc { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string codpro { get; set; }
        public string descri { get; set; }
        public decimal cant { get; set; }
        public decimal cantenv { get; set; }
    }
}
