//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class movstock
    {
        public int id { get; set; }
        public int empresaid { get; set; }
        public System.DateTime fecha { get; set; }
        public string codpro { get; set; }
        public string descri { get; set; }
        public decimal entrada { get; set; }
        public decimal salida { get; set; }
        public string detalle { get; set; }
        public string lote { get; set; }
        public string nombreusu { get; set; }
        public int ordennro { get; set; }
        public decimal costo { get; set; }
        public string despacho { get; set; }
        public System.DateTime fechafabricacion { get; set; }
        public System.DateTime fechavencimiento { get; set; }
        public int tipomovid { get; set; }
        public int ubicacionid { get; set; }
        public int ivacomid { get; set; }
        public int ivavenid { get; set; }
        public int clienteid { get; set; }
        public int proveedorid { get; set; }
        public int usuarioid { get; set; }
        public int remitoid { get; set; }
        public int movstk { get; set; }
    }
}
