//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class padronib
    {
        public string retper { get; set; }
        public decimal fechpadron { get; set; }
        public decimal fecdesde { get; set; }
        public decimal fechasta { get; set; }
        public string cuit { get; set; }
        public string tipo { get; set; }
        public string altabaja { get; set; }
        public string cambio { get; set; }
        public decimal porcentaje { get; set; }
        public decimal grupo { get; set; }
        public short juridi { get; set; }
        public long id { get; set; }
    }
}
