//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class passwd
    {
        public int idusuario { get; set; }
        public string usuario { get; set; }
        public string nombreusu { get; set; }
        public string passwd1 { get; set; }
        public int ultempresa { get; set; }
        public int ultdeposito { get; set; }
        public int ultpunto { get; set; }
        public bool essupervisor { get; set; }
        public bool esadministrador { get; set; }
        public byte proteccion { get; set; }
        public int id { get; set; }
        public int vendeasoc { get; set; }
        public bool vetodosvend { get; set; }
    }
}
