//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDet
    {
        public int id { get; set; }
        public int cabeceraid { get; set; }
        public short item { get; set; }
        public string articulo { get; set; }
        public string descri { get; set; }
        public decimal cantidad { get; set; }
        public decimal pendientes { get; set; }
        public decimal preparado { get; set; }
        public decimal precio { get; set; }
        public decimal precorig { get; set; }
        public decimal bonif { get; set; }
        public decimal bonif1 { get; set; }
        public decimal total { get; set; }
        public decimal impint { get; set; }
        public int orden { get; set; }
        public decimal marca { get; set; }
        public decimal rubro { get; set; }
        public decimal nropro { get; set; }
        public string asociado { get; set; }
        public decimal canasoc { get; set; }
        public string detalle { get; set; }
        public System.DateTime parafecha { get; set; }
        public decimal precioesp { get; set; }
        public decimal envase { get; set; }
        public decimal unimed { get; set; }
        public string moneda { get; set; }
        public decimal ivaporc1 { get; set; }
        public decimal ivaporc2 { get; set; }
        public decimal ivagrupo { get; set; }
        public decimal impiva1 { get; set; }
        public decimal impiva2 { get; set; }
        public string deta { get; set; }
        public bool listo { get; set; }
        public string codorigi { get; set; }
        public decimal uxbulto { get; set; }
        public decimal costoest { get; set; }
        public bool bajostk { get; set; }
        public decimal nrorepa { get; set; }
    }
}
