//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoCab
    {
        public int id { get; set; }
        public int empresaid { get; set; }
        public int tipodocid { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal nroped { get; set; }
        public System.DateTime fechaing { get; set; }
        public System.DateTime parafecha { get; set; }
        public int nrocli { get; set; }
        public string razsoc { get; set; }
        public decimal codven { get; set; }
        public decimal condicion { get; set; }
        public decimal cond_vta { get; set; }
        public int viaid { get; set; }
        public string via { get; set; }
        public string sucursal { get; set; }
        public decimal nrotra { get; set; }
        public string usuario { get; set; }
        public int usuarioid { get; set; }
        public string puestrotra { get; set; }
        public System.DateTime enhora { get; set; }
        public bool listo { get; set; }
        public bool completo { get; set; }
        public string preparo { get; set; }
        public string ocompra { get; set; }
        public bool aprobado { get; set; }
        public string presup { get; set; }
        public decimal lisfac { get; set; }
        public string notavta { get; set; }
        public decimal TotalNet { get; set; }
        public decimal TotalExento { get; set; }
        public decimal bonifto { get; set; }
        public decimal impiva1 { get; set; }
        public decimal impiva2 { get; set; }
        public decimal Timpint { get; set; }
        public decimal PercIB { get; set; }
        public decimal Total { get; set; }
        public bool cumplido { get; set; }
        public string monfac { get; set; }
        public int transpo { get; set; }
        public System.DateTime vence { get; set; }
        public string observa { get; set; }
        public decimal kilos { get; set; }
        public decimal bultos { get; set; }
        public string direcc { get; set; }
        public string locali { get; set; }
        public string codpos { get; set; }
        public decimal provin { get; set; }
        public int sucursalid { get; set; }
        public int localiid { get; set; }
        public string asignadoa { get; set; }
        public bool reimp { get; set; }
        public string facturado { get; set; }
        public string tipo { get; set; }
        public decimal recargo { get; set; }
        public decimal bonitot { get; set; }
    }
}
