//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class premito
    {
        public System.DateTime fecha { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal nroped { get; set; }
        public decimal nrocli { get; set; }
        public decimal subtot { get; set; }
        public decimal bonifto { get; set; }
        public decimal neto { get; set; }
        public decimal bonitot { get; set; }
        public decimal codven { get; set; }
        public string codpro { get; set; }
        public string descri { get; set; }
        public decimal cant { get; set; }
        public decimal precio { get; set; }
        public decimal bonif { get; set; }
        public decimal bonif1 { get; set; }
        public decimal prexcant { get; set; }
        public string observa { get; set; }
        public string despacho { get; set; }
        public string ocompra { get; set; }
        public int id { get; set; }
    }
}
