//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupc
    {
        public int id { get; set; }
        public int empresa { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipodocid { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public short punto { get; set; }
        public int numero { get; set; }
        public int hasta { get; set; }
        public int nrocli { get; set; }
        public string razsoc { get; set; }
        public string direcc { get; set; }
        public string locali { get; set; }
        public string codpos { get; set; }
        public decimal provin { get; set; }
        public string cuit { get; set; }
        public decimal subtot { get; set; }
        public decimal bonitot { get; set; }
        public decimal bonifto { get; set; }
        public decimal exento { get; set; }
        public decimal neto { get; set; }
        public decimal ivai { get; set; }
        public decimal ivanoi { get; set; }
        public decimal ivaidif { get; set; }
        public decimal ivanoidif { get; set; }
        public decimal total { get; set; }
        public decimal bonif { get; set; }
        public int condicion { get; set; }
        public string desccondic { get; set; }
        public decimal codven { get; set; }
        public string nomven { get; set; }
        public int respon { get; set; }
        public int tipcom { get; set; }
        public decimal comis { get; set; }
        public decimal retiva { get; set; }
        public decimal retgan { get; set; }
        public decimal retinb { get; set; }
        public decimal remito { get; set; }
        public string observa { get; set; }
        public decimal comiprod { get; set; }
        public decimal comicli { get; set; }
        public bool liquidada { get; set; }
        public decimal porins { get; set; }
        public decimal pornoi { get; set; }
        public decimal porinsdif { get; set; }
        public decimal pornoidif { get; set; }
        public System.DateTime vence { get; set; }
        public string ocompra { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public int nrorepa { get; set; }
        public int nrollevo { get; set; }
        public bool cumplido { get; set; }
        public decimal recargo { get; set; }
        public int lisfac { get; set; }
        public string atencion { get; set; }
        public string referencia { get; set; }
        public string validez { get; set; }
        public string plentrega { get; set; }
        public string lugentre { get; set; }
        public int nroped { get; set; }
        public string obsint { get; set; }
        public string nuepresup { get; set; }
        public string viejpresu { get; set; }
        public string planilla { get; set; }
        public string nombreusu { get; set; }
        public decimal costoest { get; set; }
        public decimal porcenib { get; set; }
        public decimal internos { get; set; }
        public int cond_vta { get; set; }
        public string monfac { get; set; }
        public int usuarioid { get; set; }
        public int puestotra { get; set; }
        public decimal percib { get; set; }
        public int localidadid { get; set; }
        public bool bajostk { get; set; }
    }
}
