//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class procta
    {
        public int id { get; set; }
        public int ivacomid { get; set; }
        public int empresaid { get; set; }
        public int tipodocid { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal nropro { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public decimal saldo { get; set; }
        public string tipdoco { get; set; }
        public string letrao { get; set; }
        public decimal puntoo { get; set; }
        public decimal numeroo { get; set; }
        public decimal cobro { get; set; }
        public decimal bonif { get; set; }
        public decimal impbonif { get; set; }
        public decimal retgan { get; set; }
        public decimal retiva { get; set; }
        public decimal retib { get; set; }
        public string observa { get; set; }
        public bool anulado { get; set; }
        public decimal internos { get; set; }
        public decimal retibcap { get; set; }
        public decimal regimen { get; set; }
        public System.DateTime fechafac { get; set; }
        public decimal recimanu { get; set; }
        public string nombreusu { get; set; }
        public decimal netpagado { get; set; }
        public string verifico { get; set; }
        public bool verifi { get; set; }
        public bool eschqrech { get; set; }
        public string motivo { get; set; }
        public string clave { get; set; }
        public int movcja { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public string monedacodigo { get; set; }
        public int ivacomido { get; set; }
        public int tipdocido { get; set; }
    }
}
