//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class proctad
    {
        public int id { get; set; }
        public int empresaid { get; set; }
        public int tipodocid { get; set; }
        public System.DateTime fecha { get; set; }
        public int nropro { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal importe1 { get; set; }
        public decimal importe2 { get; set; }
        public System.DateTime vence { get; set; }
        public decimal cobro { get; set; }
        public decimal porcenfac { get; set; }
        public bool eschqrech { get; set; }
        public bool retuveib { get; set; }
        public int proctaid { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public string monedacodigo { get; set; }
    }
}
