//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class provee
    {
        public int id { get; set; }
        public int nropro { get; set; }
        public string razsoc { get; set; }
        public string direcc { get; set; }
        public string direcom { get; set; }
        public int locali { get; set; }
        public string codpos { get; set; }
        public string telef1 { get; set; }
        public string telef2 { get; set; }
        public string fax { get; set; }
        public decimal expreso { get; set; }
        public string cuit { get; set; }
        public int respon { get; set; }
        public string ingbru { get; set; }
        public int zona { get; set; }
        public decimal comis { get; set; }
        public decimal condicion { get; set; }
        public string contacto { get; set; }
        public decimal credito { get; set; }
        public string email { get; set; }
        public string pweb { get; set; }
        public string califica { get; set; }
        public string observa { get; set; }
        public decimal concepto { get; set; }
        public string monfac { get; set; }
        public bool noretib { get; set; }
        public decimal porcenib { get; set; }
        public bool noretgan { get; set; }
        public bool noretiva { get; set; }
        public bool incobrable { get; set; }
        public int rg924 { get; set; }
        public string fantasia { get; set; }
        public bool visualiza { get; set; }
        public int ctacon { get; set; }
        public decimal diasvenc { get; set; }
        public string mensavenc { get; set; }
        public string celular { get; set; }
        public int ubicacionid { get; set; }
        public decimal bonif { get; set; }
        public decimal bonif1 { get; set; }
        public System.DateTime feccom { get; set; }
        public string ley { get; set; }
        public decimal lista { get; set; }
        public string cai { get; set; }
        public System.DateTime vencecai { get; set; }
        public bool convenio { get; set; }
        public int tipodoc { get; set; }
    
        public virtual condpago condpago { get; set; }
        public virtual cuentas cuentas { get; set; }
        public virtual iva iva { get; set; }
        public virtual localidades localidades { get; set; }
        public virtual monedas monedas { get; set; }
        public virtual transpo transpo { get; set; }
    }
}
