//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provincias()
        {
            this.departamentos = new HashSet<departamentos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int pais_id { get; set; }
        public int juridi { get; set; }
        public string codigoArba { get; set; }
        public bool Percib { get; set; }
        public decimal Percepib { get; set; }
        public decimal MontoPib { get; set; }
        public bool Retib { get; set; }
        public decimal Retenib { get; set; }
        public decimal montorib { get; set; }
        public decimal ctaperce { get; set; }
        public decimal ctareten { get; set; }
        public decimal ctapercep { get; set; }
        public decimal ctaretenp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<departamentos> departamentos { get; set; }
    }
}
