//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntodeVentaporEmpresa
    {
        public string empresa { get; set; }
        public int empresaid { get; set; }
        public int punto { get; set; }
        public string descripcion { get; set; }
        public bool renglonfijo { get; set; }
        public int facturaa { get; set; }
        public int debitoa { get; set; }
        public int creditoa { get; set; }
        public byte cantcopia { get; set; }
        public short cantrengla { get; set; }
        public bool multia { get; set; }
        public int facturab { get; set; }
        public int debitob { get; set; }
        public int creditob { get; set; }
        public byte cantcopib { get; set; }
        public short cantrenglb { get; set; }
        public bool multib { get; set; }
        public int facturae { get; set; }
        public int debitoe { get; set; }
        public int creditoe { get; set; }
        public byte cantcopie { get; set; }
        public short cantrengle { get; set; }
        public bool multie { get; set; }
        public bool fcelecbf { get; set; }
        public bool fcelectexp { get; set; }
        public bool fcelect { get; set; }
        public bool impfis { get; set; }
        public short comimpf { get; set; }
        public short cantrenpres { get; set; }
        public short cantcopipres { get; set; }
        public int presup { get; set; }
        public short cantrenglpedi { get; set; }
        public byte cantcopiped { get; set; }
        public int pedido { get; set; }
        public short cantrenglcompr { get; set; }
        public int ocompra { get; set; }
        public int ordenpago { get; set; }
        public byte cantcopireci { get; set; }
        public int recibo { get; set; }
        public short cantrenglremi { get; set; }
        public byte cantcopire { get; set; }
        public int remitoint { get; set; }
        public int remito { get; set; }
        public bool genemov { get; set; }
        public short cantrenglcotiz { get; set; }
        public byte cantcopicot { get; set; }
        public int cotizacion { get; set; }
    }
}
