//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitoDet
    {
        public int id { get; set; }
        public int cabeceraid { get; set; }
        public string codpro { get; set; }
        public string descri { get; set; }
        public decimal cant { get; set; }
        public decimal precio { get; set; }
        public decimal bonif { get; set; }
        public decimal bonif1 { get; set; }
        public decimal prexcant { get; set; }
        public bool bajostk { get; set; }
        public string asociado { get; set; }
        public decimal canasoc { get; set; }
        public decimal pedido { get; set; }
        public string despacho { get; set; }
        public string unimed { get; set; }
        public string envase { get; set; }
        public decimal cantenv { get; set; }
        public string deta { get; set; }
        public string ocompra { get; set; }
        public int nroped { get; set; }
        public decimal porcen1 { get; set; }
        public decimal porcen2 { get; set; }
        public decimal impiva1 { get; set; }
        public decimal impiva2 { get; set; }
        public decimal uxbulto { get; set; }
        public string cbarras { get; set; }
        public string codorigi { get; set; }
        public decimal kilos { get; set; }
        public int bultos { get; set; }
        public string tipofac { get; set; }
        public string letrafac { get; set; }
        public decimal puntofac { get; set; }
        public decimal nrofac { get; set; }
    }
}
