//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitoCab
    {
        public int id { get; set; }
        public int empresaid { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipodoc { get; set; }
        public int tipodocid { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal hasta { get; set; }
        public int nrocli { get; set; }
        public decimal subtot { get; set; }
        public decimal bonifto { get; set; }
        public decimal neto { get; set; }
        public decimal bonitot { get; set; }
        public int codven { get; set; }
        public decimal valdec { get; set; }
        public string facturado { get; set; }
        public int nrotra { get; set; }
        public int provin { get; set; }
        public int respon { get; set; }
        public string direcc { get; set; }
        public string locali { get; set; }
        public int localiid { get; set; }
        public string codpos { get; set; }
        public string nombreusu { get; set; }
        public decimal impint { get; set; }
        public decimal acopionro { get; set; }
        public decimal nrorep { get; set; }
        public bool cumplido { get; set; }
        public string notavta { get; set; }
        public string detped { get; set; }
        public string nrolibe { get; set; }
        public string contac { get; set; }
        public string guia { get; set; }
        public System.DateTime fechades { get; set; }
        public string sucursal { get; set; }
        public string direntrega { get; set; }
        public string obsrepa { get; set; }
        public int transrep { get; set; }
        public string observa { get; set; }
        public int ivavenid { get; set; }
        public decimal kilos { get; set; }
        public int bultos { get; set; }
        public string razsoc { get; set; }
        public int lisfac { get; set; }
        public int condicion { get; set; }
        public int cond_vta { get; set; }
        public System.DateTime vence { get; set; }
        public string monfac { get; set; }
        public int nroped { get; set; }
        public int usuarioid { get; set; }
        public string puestotra { get; set; }
        public decimal exento { get; set; }
        public decimal ivai { get; set; }
        public decimal ivaidif { get; set; }
        public decimal ivanoi { get; set; }
        public decimal ivanoidif { get; set; }
        public decimal percib { get; set; }
        public decimal total { get; set; }
        public decimal nrotran { get; set; }
        public short listanro { get; set; }
        public string cotnro { get; set; }
        public decimal recargo { get; set; }
        public int transpo { get; set; }
    }
}
