//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubros
    {
        public int id { get; set; }
        public int codigo { get; set; }
        public string descri { get; set; }
        public string pathfoto { get; set; }
        public decimal dr1 { get; set; }
        public decimal dr2 { get; set; }
        public decimal dr3 { get; set; }
        public decimal dr4 { get; set; }
        public decimal dr5 { get; set; }
        public decimal rubmar1 { get; set; }
        public decimal rubmar2 { get; set; }
        public decimal rubmar3 { get; set; }
        public decimal rubmar4 { get; set; }
        public decimal rubmar5 { get; set; }
        public decimal rubmar6 { get; set; }
        public bool incluac { get; set; }
        public bool mostrarweb { get; set; }
    }
}
