//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class RWRefCliente
    {
        public decimal nrocli { get; set; }
        public string cargo { get; set; }
        public string apenom { get; set; }
        public System.DateTime fecnac { get; set; }
        public string direcc { get; set; }
        public string telefono { get; set; }
        public string observ { get; set; }
        public string email { get; set; }
        public int id { get; set; }
        public string razsoc { get; set; }
    }
}
