//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int id { get; set; }
        public string codpro { get; set; }
        public string cbarras { get; set; }
        public string dun14 { get; set; }
        public string codorigi { get; set; }
        public string coriginal { get; set; }
        public string codncm { get; set; }
        public string descri { get; set; }
        public string despacho { get; set; }
        public string verifico { get; set; }
        public string color { get; set; }
        public string pathfoto { get; set; }
        public string pathetiq { get; set; }
        public string usuestr { get; set; }
        public string descrilar { get; set; }
        public string usoart { get; set; }
        public string observa { get; set; }
        public int rubro { get; set; }
        public decimal subrub { get; set; }
        public decimal marca { get; set; }
        public decimal unimed { get; set; }
        public decimal proveed { get; set; }
        public string moneda { get; set; }
        public decimal envase { get; set; }
        public decimal ivagrupo { get; set; }
        public int ctacon { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fecmodcos { get; set; }
        public System.DateTime alta { get; set; }
        public System.DateTime fechaact { get; set; }
        public System.DateTime fechveri { get; set; }
        public System.DateTime fecprom { get; set; }
        public System.DateTime fechestr { get; set; }
        public System.DateTime fechpped { get; set; }
        public System.DateTime cosfverif { get; set; }
        public bool incluido { get; set; }
        public bool artret { get; set; }
        public bool oferta { get; set; }
        public bool descomp { get; set; }
        public bool vtaxbul { get; set; }
        public bool discont { get; set; }
        public bool noborrarelart { get; set; }
        public bool msgstkptoped { get; set; }
        public decimal costo { get; set; }
        public decimal precio1 { get; set; }
        public decimal precio2 { get; set; }
        public decimal precio3 { get; set; }
        public decimal precio4 { get; set; }
        public decimal precio5 { get; set; }
        public decimal precio6 { get; set; }
        public decimal stomin { get; set; }
        public decimal ppedido { get; set; }
        public decimal boniprod { get; set; }
        public decimal comiprod { get; set; }
        public decimal comipcob { get; set; }
        public decimal cantenv { get; set; }
        public decimal peso { get; set; }
        public decimal promedio { get; set; }
        public decimal meses { get; set; }
        public decimal canths { get; set; }
        public decimal uxbulto { get; set; }
        public decimal prelis { get; set; }
        public int tipoart { get; set; }
        public decimal impint { get; set; }
        public decimal impasoc { get; set; }
        public decimal presug { get; set; }
        public decimal cantmin { get; set; }
        public decimal porceasoc { get; set; }
        public decimal internos { get; set; }
        public bool modifdescr { get; set; }
        public string coddisp { get; set; }
        public string codsku { get; set; }
        public decimal uxdisp { get; set; }
        public bool exigelote { get; set; }
        public string codcot { get; set; }
        public bool sinprec { get; set; }
        public bool factucomp { get; set; }
        public int codcolor { get; set; }
        public decimal ds1 { get; set; }
        public decimal ds2 { get; set; }
        public decimal ds3 { get; set; }
        public decimal ds4 { get; set; }
        public decimal ds5 { get; set; }
        public bool execf { get; set; }
        public string CodMedia { get; set; }
        public decimal uxmedia { get; set; }
    }
}
