//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipocomprobante
    {
        public int codigo { get; set; }
        public string descri { get; set; }
        public string abreviado { get; set; }
        public string letra { get; set; }
        public bool discrimina { get; set; }
        public bool activo { get; set; }
        public bool retieneiva { get; set; }
        public bool esDebito { get; set; }
        public bool esCredito { get; set; }
        public bool esAfip { get; set; }
        public bool esdePago { get; set; }
        public bool seAnula { get; set; }
        public string numerador { get; set; }
        public string copias { get; set; }
        public string renglones { get; set; }
        public string codigoARBA { get; set; }
        public int id { get; set; }
    }
}
