//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class transpo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transpo()
        {
            this.provee = new HashSet<provee>();
        }
    
        public int id { get; set; }
        public decimal codigo { get; set; }
        public string razsoc { get; set; }
        public string direcc { get; set; }
        public int locali { get; set; }
        public string codpos { get; set; }
        public string telefo { get; set; }
        public string cuit { get; set; }
        public string ingbru { get; set; }
        public string observa { get; set; }
        public string horario { get; set; }
        public string contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provee> provee { get; set; }
    }
}
