//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class UbicacionporDepositoEmpresa
    {
        public Nullable<int> empresaid { get; set; }
        public string empresa { get; set; }
        public int depositoid { get; set; }
        public string deposito { get; set; }
        public int id { get; set; }
        public string ubicacion { get; set; }
        public string descripcion { get; set; }
        public bool permiteEntrada { get; set; }
        public bool permiteSalida { get; set; }
    }
}
