//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class usu_acce
    {
        public int id { get; set; }
        public int idempresa { get; set; }
        public int idusuario { get; set; }
        public int idacceso { get; set; }
        public bool alta { get; set; }
        public bool baja { get; set; }
        public bool modif { get; set; }
    }
}
