//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class VArtVen
    {
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public int empresa { get; set; }
        public decimal numero { get; set; }
        public string codpro { get; set; }
        public string descri { get; set; }
        public decimal cant { get; set; }
        public decimal precio { get; set; }
        public decimal prexcant { get; set; }
        public decimal bonitot { get; set; }
        public string nombre { get; set; }
        public decimal codven { get; set; }
        public decimal nrocli { get; set; }
        public string razsoc { get; set; }
        public System.DateTime fecha { get; set; }
        public int marca { get; set; }
        public int rubro { get; set; }
        public decimal subrub { get; set; }
    }
}
