//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCobranzas
    {
        public Nullable<System.DateTime> fecha { get; set; }
        public string razsoc { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal numero { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<decimal> neto { get; set; }
        public Nullable<decimal> comis { get; set; }
        public decimal comiprod { get; set; }
        public Nullable<decimal> comicli { get; set; }
        public decimal comicob { get; set; }
        public decimal comicocl { get; set; }
        public Nullable<bool> liquidada { get; set; }
        public string letrao { get; set; }
        public string tipdoco { get; set; }
        public int empresao { get; set; }
        public decimal numeroo { get; set; }
        public Nullable<decimal> codven { get; set; }
        public Nullable<decimal> comisionVende { get; set; }
        public Nullable<decimal> comisionProducto { get; set; }
        public Nullable<decimal> comisionCliente { get; set; }
        public Nullable<decimal> netoCobradoVend { get; set; }
        public Nullable<decimal> netoCobradoProd { get; set; }
        public Nullable<decimal> netoCobradoCli { get; set; }
        public decimal punto { get; set; }
        public decimal puntoo { get; set; }
        public string nomven { get; set; }
    }
}
