//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistacomprabantepresupuesto
    {
        public int id { get; set; }
        public int cabeceraid { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime hora { get; set; }
        public string tipodoc { get; set; }
        public string letra { get; set; }
        public decimal punto { get; set; }
        public decimal numero { get; set; }
        public decimal remito { get; set; }
        public string codpro { get; set; }
        public string descri { get; set; }
        public decimal cant { get; set; }
        public decimal precio { get; set; }
        public decimal bonif { get; set; }
        public decimal bonif1 { get; set; }
        public decimal prexcant { get; set; }
        public decimal costo { get; set; }
        public decimal ivartins { get; set; }
        public decimal ivartinoi { get; set; }
        public decimal bonito { get; set; }
        public decimal nrocli { get; set; }
        public string asociado { get; set; }
        public decimal canasoc { get; set; }
        public decimal pedido { get; set; }
        public string despacho { get; set; }
        public string simbolo { get; set; }
        public decimal cotizacion { get; set; }
        public string unimed { get; set; }
        public string envase { get; set; }
        public decimal cantenv { get; set; }
        public decimal pins { get; set; }
        public decimal pnoi { get; set; }
        public string deta { get; set; }
        public decimal aprobados { get; set; }
        public string detalle { get; set; }
        public decimal impint { get; set; }
        public decimal precorig { get; set; }
        public decimal ivaporc1 { get; set; }
        public decimal ivaporc2 { get; set; }
        public string moneda { get; set; }
        public string pathfoto { get; set; }
    }
}
