//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRemitos
    {
        public string razsoc { get; set; }
        public decimal subtot { get; set; }
        public decimal bonitot { get; set; }
        public decimal bonifto { get; set; }
        public decimal neto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string letra { get; set; }
        public int empresaid { get; set; }
        public decimal numero { get; set; }
        public string facturado { get; set; }
    }
}
