//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSaldoCli
    {
        public Nullable<System.DateTime> fecha { get; set; }
        public int nrocli { get; set; }
        public string razsoc { get; set; }
        public decimal saldo { get; set; }
        public string zona { get; set; }
        public int id { get; set; }
        public string vemdedor { get; set; }
        public decimal codven { get; set; }
    }
}
