//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVendedores
    {
        public decimal codven { get; set; }
        public string VendeNom { get; set; }
        public string telefo { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public int locali { get; set; }
        public string nombre { get; set; }
        public string direcc { get; set; }
        public int tipdoc { get; set; }
        public decimal numdoc { get; set; }
        public decimal comicob { get; set; }
        public decimal comision { get; set; }
        public decimal saldo { get; set; }
    }
}
